Feature/gitpod
graphcommerce-org/graphcommerce pull request #1340
Opened 2022-03-18 10:47 UTC by collymore

Added a Gitpod file to allow developing with GraphCommerce in Gitpod

2022-03-18 11:31 UTC, collymore commented
Here's a preview of how it works if you're not familiar with gitpod 
https://www.youtube.com/watch?v=aTIzFMj9p0Y

2022-03-21 15:25 UTC, paales requested changes
Very cool @collymore! I haven't used gitpod per sé, but it would be very nice to add support for it (as well as all the other cloud editors like stackblitz / codesandbox).

I'm running into an issue when I'm using it, that is because we have a `NEXT_PUBLIC_GRAPHQL_ENDPOINT` variable, let me see if we can do something about that.

<img width="1894" alt="Schermafbeelding 2022-03-21 om 16 23 56" src="https://user-images.githubusercontent.com/1244416/159293888-846575d5-833e-4ced-b8fa-cb636211610c.png">

2022-03-21 15:25 UTC, paales commented on .gitpod.yml
> +      cd my-project
If we just want to spin up an example, it is also possible to just do:

```suggestion
      cd examples/magento-graphcms
```

2022-03-21 15:25 UTC, paales commented on .gitpod.yml
> +      rm CHANGELOG.md && touch CHANGELOG.md
Make it inline with the most recent 
```suggestion
      rm CHANGELOG.md
```

2022-03-21 15:26 UTC, paales commented on .gitpod.yml
> +    command: cd /workspace/graphcommerce/my-project && npm run dev
```suggestion
    command: cd /workspace/graphcommerce/examples/magento-graphcms && npm run dev
```

2022-03-21 15:53 UTC, paales commented
@collymore We do have the `GITPOD_WORKSPACE_URL` env variable available. And the eventual URL the instance runs on is `3000-$GITPOD_WORKSPACE_URL`. Maybe we can do something with that?

2022-03-21 17:06 UTC, collymore commented
> @collymore We do have the `GITPOD_WORKSPACE_URL` env variable available. And the eventual URL the instance runs on is `3000-$GITPOD_WORKSPACE_URL`. Maybe we can do something with that?

Yes that will always be the correct URL. Also there is  ```gp url``` available this will print the current url on the cli 
<img width="462" alt="Screenshot 2022-03-21 at 17 03 34" src="https://user-images.githubusercontent.com/55946/159326254-cb899d3a-d696-44cd-a44d-1552e226986b.png">

2022-03-21 22:44 UTC, collymore commented
@paales https://github.com/collymore/graphcommerce/commit/a1bb3917900a8d8d9a9a9d0204c6b3d7f4e73f01 fixes the NEXT_PUBLIC_GRAPHQL_ENDPOINT variable issue

2022-03-22 08:59 UTC, paales commented
@collymore There are two directions we can go with this:

1. The current 'root' graphcommerce .gitpod assumes the monorepo is present and we are effectively setting up the monorepo and starting the current example.
2. There could be an `examples/magento-graphcms/.gitpod.yml`  that allows you to start the .gitpod by copying the example by replicating https://www.graphcommerce.org/docs/getting-started/create

I've now changed the .gitpod file to make it work with the monorepo.

2022-03-22 09:41 UTC, paales approved these changes

2022-03-23 12:38 UTC, merged

2022-03-23 12:39 UTC, paales commented
@collymore Merged!