Feature/shipping methods
graphcommerce-org/graphcommerce pull request #1515
Opened 2022-06-14 07:21 UTC by mikekeehnen

2022-06-14 11:16 UTC, paales requested changes

2022-06-14 11:47 UTC, paales requested changes

2022-06-14 11:59 UTC, mikekeehnen commented on packages/next-ui/Theme/MuiButton.ts
> +      margin: `calc(${theme.spacings.sm} * -1 + 8px)`,
Ik had deze inderdaad moeten berekenen, heb het bijgewerkt

2022-06-14 12:00 UTC, mikekeehnen commented on packages/next-ui/Theme/MuiButton.ts
> +    }),
Alle changes in de MuiButton.ts file? Deze vangen juist de styling op wanneer je kiest voor de inline variant toch?

2022-06-14 12:02 UTC, mikekeehnen commented on packages/next-ui/Theme/MuiButton.ts
> +    }),
Klopt inderdaad, heb ze weggehaald

2022-06-15 07:29 UTC, paales approved these changes

2022-06-15 07:29 UTC, merged