Fix/navigation in dom
graphcommerce-org/graphcommerce pull request #1806
Opened 2023-02-17 16:07 UTC by ErwinOtten

2023-02-20 07:38 UTC, paales requested changes

2023-02-20 07:38 UTC, paales commented on packages/next-ui/Overlay/components/OverlayBase.tsx
> +              {typeof children === 'function' ? children() : children}
Something like this?
 
```suggestion
              {typeof children === 'function' ? (active && children()) : children}
```

2023-02-20 08:54 UTC, ErwinOtten commented on packages/next-ui/Overlay/components/OverlayBase.tsx
> +              {typeof children === 'function' ? children() : children}
Fixed

2023-02-21 16:05 UTC, paales approved these changes

2023-02-21 16:05 UTC, merged