feat: add open graph tags to all pages
graphcommerce-org/graphcommerce pull request #1961
Opened 2023-06-13 08:32 UTC by Giovanni-Schroevers

2023-06-13 11:02 UTC, paales requested changes

2023-06-13 11:02 UTC, paales commented on packages/magento-product/components/ProductPageMeta/ProductPageMeta.tsx
>            <meta property='type' content='product' key='og-type' />
We're using a type here, but later we're using og:type. Is that something we need to move to PageMeta as well?

2023-06-13 11:02 UTC, paales commented on packages/next-ui/PageMeta/PageMeta.tsx
> +  openGraphImage?: string | null
Rename to ogImage?

2023-06-13 11:02 UTC, paales commented on packages/next-ui/PageMeta/PageMeta.tsx
> +      <meta property='og:type' content='website' />
See above comment, what is the difference between og:type and type?

2023-06-20 11:14 UTC, paales requested changes

2023-06-21 12:17 UTC, Giovanni-Schroevers commented on packages/magento-category/components/CategoryHeroNav/CategoryHeroNav.graphql
> +  image
This is used in `examples/magento-graphcms/pages/[...url].tsx` but this should have been done in `CategoryMeta`

2023-06-22 12:28 UTC, merged