[GCOM-1112] collapse limit section
graphcommerce-org/graphcommerce pull request #1975
Opened 2023-06-27 13:50 UTC by JoshuaS98

2023-06-28 14:42 UTC, paales requested changes

2023-06-28 14:42 UTC, paales commented on .changeset/three-bees-tickle.md
> +'@graphcommerce/magento-product': minor
patch

2023-06-30 08:58 UTC, paales commented on .changeset/three-bees-tickle.md
> +'@graphcommerce/magento-product': minor
Dit is een minor release, maar een patch

2023-07-04 09:27 UTC, mikekeehnen commented on packages/magento-product/components/ProductFiltersPro/ProductFiltersProLimitSection.tsx
> +      defaultExpanded={!!activePageSize}
```suggestion
      defaultExpanded={Boolean(activePageSize)}
```

2023-07-13 08:00 UTC, merged