Fixed overlays closing while still dragging
graphcommerce-org/graphcommerce pull request #1980
Opened 2023-06-30 10:27 UTC by bramvanderholst

Overlays should only close after releasing pointer

2023-07-07 10:12 UTC, paales requested changes

2023-07-07 10:12 UTC, paales commented on packages/next-ui/Overlay/components/OverlayBase.tsx
> +    dragging = true
```suggestion
    dragging.set(true)
```

2023-07-07 10:12 UTC, paales commented on packages/next-ui/Overlay/components/OverlayBase.tsx
> +    dragging = false
```suggestion
    dragging.set(false)
```

2023-07-07 10:12 UTC, paales commented on packages/next-ui/Overlay/components/OverlayBase.tsx
> +    (o) => o === 0 && !dragging && closeOverlay(),
```suggestion
    (o) => o === 0 && !dragging.get() && closeOverlay(),
```

2023-07-24 08:35 UTC, bramvanderholst commented
@paales The requested changes have been implemented.

2023-08-04 11:00 UTC, merged