Bug/gcom 1210 broken product image animation
graphcommerce-org/graphcommerce pull request #2085
Opened 2023-10-11 12:04 UTC by Jessevdpoel

2023-10-11 12:15 UTC, paales requested changes

2023-10-11 12:15 UTC, paales commented on packages/framer-scroller/components/ScrollerButton.tsx
> +    const [isScrolling, setIsScrolling] = useState(false)
```suggestion
     const isScrolling = useRef(false)
```

2023-10-11 12:15 UTC, paales commented on packages/framer-scroller/components/ScrollerButton.tsx
> +      }
```suggestion
      if (!isScrolling.current) {
        isScrolling.current = true
        await scrollTo(getSnapPosition(direction))
        isScrolling.current =  false
      }
```

2023-10-12 07:52 UTC, mikekeehnen commented on packages/framer-scroller/components/ScrollerButton.tsx
> +      if (!isScrolling.current) {
I think we already have a `scroll.animating`. You can use that variable to catch the "spammed" click

2023-10-19 08:16 UTC, paales requested changes
See changes from @mikekeehnen

2023-10-20 08:26 UTC, paales commented on packages/framer-scroller/components/ScrollerButton.tsx
> +import React, { useRef } from 'react'
Not used

2023-10-20 08:27 UTC, paales approved these changes
This looks great! Last thing, can you clean up unused useRef?

Can we also create a followup ticket that will allow animating to the _next_ item when clicked multiple times?

2023-10-24 04:57 UTC, merged