feat(GCOM-1245): autofocus email field in checkout
graphcommerce-org/graphcommerce pull request #2102
Opened 2023-10-25 13:07 UTC by FrankHarland

2023-11-03 10:17 UTC, paales requested changes

2023-11-03 10:17 UTC, paales commented on packages/magento-cart-email/EmailForm/EmailForm.tsx
> +            autoFocus: true,
Do we always want to autoFocus this? Maybe better to pass this by a prop, seems a configuration specific to the place where the component is used.

2024-01-04 13:10 UTC, paales commented
Marked this as stale, not sure if we should proceed, you had some second thoughts?

2024-01-09 11:43 UTC, FrankHarland commented
> Marked this as stale, not sure if we should proceed, you had some second thoughts?

@paales Yes, while working on the a11y improvements I found multiple sources claiming autofocus to be possibly quite annoying for impaired users. In the newer GC versions we even have a seperate button offering the user a choice between signin and registration. If we autofocus the field we bypass this option and things can get confusing.

So I think it might be better to just scrap this PR.

2024-01-23 16:05 UTC, closed without merging