Feature/guest only mode
graphcommerce-org/graphcommerce pull request #2218
Opened 2024-02-23 11:17 UTC by Jessevdpoel

2024-02-23 11:27 UTC, paales requested changes

2024-02-23 11:27 UTC, paales commented on packages/magento-cart/components/InlineAccount/InlineAccount.tsx
>    )
Please use early returns instead of wrapping:

```
if (import.meta.graphCommerce.guestOnlyMode) return null
```

2024-02-23 11:27 UTC, paales commented on examples/magento-graphcms/pages/404.tsx
> +    )
Use an if statement instead of an expression

2024-03-12 09:48 UTC, paales approved these changes

2024-08-22 13:15 UTC, Giovanni-Schroevers commented
`packages/magento-cart/components/ApolloCartError/ApolloCartErrorAlert.tsx`
![Screenshot 2024-08-22 at 15 14 22](https://github.com/user-attachments/assets/72a319d3-4b6c-4156-9803-1637d5a8866b)

2024-09-04 09:12 UTC, closed without merging