feat(GCOM-1352): improve sorting and sortingoptions on search and category pages
graphcommerce-org/graphcommerce pull request #2227
Opened 2024-03-22 12:56 UTC by FrankHarland

2024-04-04 12:44 UTC, paales requested changes

2024-04-10 11:57 UTC, FrankHarland commented on packages/magento-product/components/ProductFiltersPro/handleSort.ts
> +}
Done!

2024-04-10 11:57 UTC, FrankHarland commented on packages/magento-product/hooks/useProductListLink.ts
> +  if (sort && sortBy && sort[sortBy] && sort[sortBy] === 'DESC') query += `/dir/DESC`
Done!

2024-04-10 12:18 UTC, paales approved these changes

2024-04-22 20:30 UTC, merged